# Generated by Django 3.2 on 2023-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Бургер',
                'verbose_name_plural': 'Бургеры',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price30', models.DecimalField(decimal_places=0, max_digits=5)),
                ('price36', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
                ('composition', models.TextField()),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
            },
        ),
        migrations.CreateModel(
            name='Rolls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Роллы',
                'verbose_name_plural': 'Роллы',
            },
        ),
        migrations.CreateModel(
            name='Salads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
                ('composition', models.TextField()),
            ],
            options={
                'verbose_name': 'Салат',
                'verbose_name_plural': 'Салаты',
            },
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Сет',
                'verbose_name_plural': 'Сеты',
            },
        ),
    ]
